version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: challenge
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - cdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  cdata:
