#!/bin/sh

container_id=$(docker ps -qf "name=app")

if [ -z "$container_id" ]; then
    echo "Could not find container ID, make sure it is up and running."
    exit 1
fi

docker exec -it $container_id bash
