package com.diveedi.storage.entity;

import io.github.ulisse1996.jaorm.annotation.Cacheable;
import io.github.ulisse1996.jaorm.annotation.Column;
import io.github.ulisse1996.jaorm.annotation.Id;
import io.github.ulisse1996.jaorm.annotation.Table;

import java.math.BigDecimal;

@Table(name = "TLCDOCS")
@Cacheable
public class TLCDOCS {
    @Id(autoGenerated = true)
    @Column(name = "id")
    private int id;

    @Column(name = "name")
    private String name;

    @Column(name = "created_at")
    private BigDecimal createdAt;

    @Column(name = "updated_at")
    private BigDecimal updatedAt;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BigDecimal getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(BigDecimal createdAt) {
        this.createdAt = createdAt;
    }

    public BigDecimal getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(BigDecimal updatedAt) {
        this.updatedAt = updatedAt;
    }
}
