package com.diveedi.storage.entity;

import io.github.ulisse1996.jaorm.annotation.Cacheable;
import io.github.ulisse1996.jaorm.annotation.Column;
import io.github.ulisse1996.jaorm.annotation.Id;
import io.github.ulisse1996.jaorm.annotation.Table;

import java.math.BigDecimal;

@Table(name = "TLCPERS")
@Cacheable
public class TLCPERS {
    @Id(autoGenerated = true)
    @Column(name = "id")
    private int id;

    @Column(name = "first_name")
    private String firstName;

    @Column(name = "last_name")
    private String lastName;

    @Column(name = "birth_date")
    private BigDecimal birthDate;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public BigDecimal getBirthDate() {
        return birthDate;
    }

    public void setBirthDate(BigDecimal birthDate) {
        this.birthDate = birthDate;
    }
}
